### PR TITLE
Added parsing Grive Files/folders URL For Extraction and compressed. 

### PR DESCRIPTION
**Pull request by norm-git**

### CODE REVIEW

**Comment by alok99-git** [comment]
> _No description provided._

I think you forget to giving credits for original commit

**Comment by norm-git** [comment]
> > _No description provided._
> 
> I think you forget to giving credits for original commit

I know but it was for another purpose, to upload telegram, although it was not taken into account.

**Comment by anasty17** [comment]
> > > _No description provided._
> > 
> > 
> > I think you forget to giving credits for original commit
> 
> I know but it was for another purpose, to upload telegram, although it was not taken into account.

This is my commit ..... don't ask for it while you trying to report our repo ... weird people

**Comment by norm-git** [comment]
> > > > _No se proporcionó descripción._
> > > 
> > > 
> > > Creo que te olvidas de dar créditos por el compromiso original.
> > 
> > 
> > Lo sé pero fue para otro propósito, subir telegrama, aunque no se tuvo en cuenta.
> 
> Este es mi compromiso ... no lo pidas mientras intentas informar nuestro repositorio ... gente extraña



> > > > _No description provided._
> > > 
> > > 
> > > I think you forget to giving credits for original commit
> > 
> > 
> > I know but it was for another purpose, to upload telegram, although it was not taken into account.
> 
> This is my commit ..... don't ask for it while you trying to report our repo ... weird people


> > > > _No description provided._
> > > 
> > > 
> > > I think you forget to giving credits for original commit
> > 
> > 
> > I know but it was for another purpose, to upload telegram, although it was not taken into account.
> 
> This is my commit ..... don't ask for it while you trying to report our repo ... weird people

Dont worry, this repo is [unmaintained](https://github.com/ksssomesh12/tg-mirror-bot/issues/34).

**Pull request closed without merging**
